# Generated by Django 5.2.7 on 2025-11-20 06:15

import Common.validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings', max_length=500)),
                ('pricing_type', models.CharField(choices=[('simple', 'Simple Pricing'), ('tiered', 'Tiered Pricing'), ('day_based', 'Day-Based Pricing'), ('tier_and_day', 'Tiered + Day-Based')], default='simple', help_text='Pricing structure for tickets in this event', max_length=20)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_address', models.TextField()),
                ('venue_city', models.CharField(max_length=100)),
                ('venue_state', models.CharField(blank=True, max_length=100)),
                ('venue_country', models.CharField(max_length=100)),
                ('venue_postal_code', models.CharField(blank=True, max_length=20)),
                ('venue_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='For map integration', max_digits=9, null=True)),
                ('venue_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='For map integration', max_digits=9, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/%Y/%m/', validators=[Common.validators.ImageSizeValidator(max_size_mb=5), Common.validators.ImageExtensionValidator()])),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/%Y/%m/', validators=[Common.validators.ImageSizeValidator(max_size_mb=5), Common.validators.ImageExtensionValidator()])),
                ('total_capacity', models.PositiveIntegerField(help_text='Total number of attendees allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Starting price (if not free)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('refund_policy', models.TextField(blank=True)),
                ('age_restriction', models.PositiveIntegerField(blank=True, help_text='Minimum age requirement (e.g., 18)', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
    ]
