# Generated by Django 5.2.7 on 2025-11-03 19:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings', max_length=500)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_address', models.TextField()),
                ('venue_city', models.CharField(max_length=100)),
                ('venue_state', models.CharField(blank=True, max_length=100)),
                ('venue_country', models.CharField(max_length=100)),
                ('venue_postal_code', models.CharField(blank=True, max_length=20)),
                ('venue_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='For map integration', max_digits=9, null=True)),
                ('venue_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='For map integration', max_digits=9, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/%Y/%m/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/%Y/%m/')),
                ('total_capacity', models.PositiveIntegerField(help_text='Total number of attendees allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Starting price (if not free)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('refund_policy', models.TextField(blank=True)),
                ('age_restriction', models.PositiveIntegerField(blank=True, help_text='Minimum age requirement (e.g., 18)', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(limit_choices_to={'user_type': 'organizer'}, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='Events.eventcategory')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['-start_date'], name='Events_even_start_d_4a4b5f_idx'), models.Index(fields=['status'], name='Events_even_status_787c17_idx'), models.Index(fields=['organizer'], name='Events_even_organiz_528a70_idx'), models.Index(fields=['category'], name='Events_even_categor_08f184_idx')],
            },
        ),
    ]
