# Generated by Django 5.2.7 on 2025-11-05 04:36

import Common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/%Y/%m/', validators=[Common.validators.ImageSizeValidator(max_size_mb=5), Common.validators.ImageExtensionValidator()]),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/thumbnails/%Y/%m/', validators=[Common.validators.ImageSizeValidator(max_size_mb=5), Common.validators.ImageExtensionValidator()]),
        ),
    ]
