# Generated by Django 5.2.7 on 2025-11-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_banner_image_alter_event_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pricing_type',
            field=models.CharField(choices=[('simple', 'Simple Pricing'), ('tiered', 'Tiered Pricing'), ('day_based', 'Day-Based Pricing'), ('tier_and_day', 'Tiered + Day-Based')], default='simple', help_text='Pricing structure for tickets in this event', max_length=20),
        ),
    ]
