# Generated by Django 5.2.7 on 2025-11-20 06:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField(blank=True, help_text='Day number (null for All Days pass)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(help_text='E.g., Day 1, Day 2, All Days Pass', max_length=50)),
                ('date', models.DateField(blank=True, help_text='Specific date for this day pass', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(help_text='Number of passes available for this day', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_all_days', models.BooleanField(default=False, help_text="True if this is an 'All Days' pass")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Day Pass',
                'verbose_name_plural': 'Day Passes',
                'ordering': ['ticket_type', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='DayTierPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField(help_text='Day number (1, 2, 3, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('day_name', models.CharField(help_text='E.g., Day 1, Day 2, Friday, Saturday', max_length=50)),
                ('date', models.DateField(blank=True, help_text='Specific date for this day', null=True)),
                ('tier_number', models.PositiveIntegerField(help_text='Tier level (1 = VIP/highest, 2 = General, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('tier_name', models.CharField(help_text='E.g., VIP, General Admission, Regular', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this Day + Tier combination', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(help_text='Number of tickets available for this Day + Tier combination', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Number sold for this combination')),
                ('sales_start', models.DateTimeField(blank=True, null=True)),
                ('sales_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this combination currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Day + Tier Price',
                'verbose_name_plural': 'Day + Tier Prices',
                'ordering': ['ticket_type', 'day_number', 'tier_number'],
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_number', models.PositiveIntegerField(help_text='Tier level (1 = cheapest, higher = more expensive)', validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(help_text='E.g., Tier 1, Tier 2, Early Bird', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(help_text='Number of tickets in this tier', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('sales_start', models.DateTimeField(blank=True, null=True)),
                ('sales_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket Tier',
                'verbose_name_plural': 'Ticket Tiers',
                'ordering': ['ticket_type', 'tier_number'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='E.g., VIP Pass, General Admission, Early Bird', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pricing_type', models.CharField(choices=[('simple', 'Simple Pricing'), ('tiered', 'Tiered Pricing'), ('day_based', 'Day-Based Pricing'), ('tier_and_day', 'Tiered + Day-Based')], default='simple', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Used only for simple pricing type', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_quantity', models.PositiveIntegerField(help_text='Total tickets available for this type', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Number of tickets sold')),
                ('sales_start', models.DateTimeField(blank=True, help_text='When ticket sales begin (optional)', null=True)),
                ('sales_end', models.DateTimeField(blank=True, help_text='When ticket sales end (optional)', null=True)),
                ('min_purchase', models.PositiveIntegerField(default=1, help_text='Minimum tickets per purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_purchase', models.PositiveIntegerField(default=10, help_text='Maximum tickets per purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('benefits', models.TextField(blank=True, help_text='Special benefits/perks (e.g., VIP lounge access, merch)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
                'ordering': ['event', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, help_text='Human-readable ticket number (auto-generated)', max_length=30, unique=True)),
                ('ticket_name', models.CharField(help_text='Ticket type name at time of creation', max_length=255)),
                ('tier_name', models.CharField(blank=True, help_text='Tier name if applicable', max_length=100)),
                ('day_name', models.CharField(blank=True, help_text='Day pass name if applicable', max_length=100)),
                ('event_date', models.DateTimeField(help_text='Event date/time (snapshot)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price paid for this ticket', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('qr_code_data', models.CharField(blank=True, help_text='Unique QR code data for verification', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_used', models.BooleanField(default=False, help_text='Has ticket been scanned?')),
                ('used_at', models.DateTimeField(blank=True, help_text='When ticket was scanned', null=True)),
                ('attendee_name', models.CharField(blank=True, help_text='Name of person attending with this ticket', max_length=255)),
                ('attendee_email', models.EmailField(blank=True, help_text='Email of person attending', max_length=254)),
                ('attendee_phone', models.CharField(blank=True, help_text='Phone of person attending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_pass', models.ForeignKey(blank=True, help_text="For 'day_based' pricing: Specific day pass", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.daypass')),
                ('day_tier_price', models.ForeignKey(blank=True, help_text="For 'tier_and_day' pricing: Specific Day+Tier combination", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.daytierprice')),
                ('event', models.ForeignKey(help_text='Event this ticket is for', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Events.event')),
                ('order_item', models.ForeignKey(help_text='The order item this ticket belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Orders.orderitem')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
