# Generated by Django 5.2.7 on 2025-11-03 20:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='E.g., VIP Pass, General Admission, Early Bird', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pricing_type', models.CharField(choices=[('simple', 'Simple Pricing'), ('tiered', 'Tiered Pricing'), ('day_based', 'Day-Based Pricing'), ('tier_and_day', 'Tiered + Day-Based')], default='simple', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Used only for simple pricing type', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_quantity', models.PositiveIntegerField(help_text='Total tickets available for this type', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Number of tickets sold')),
                ('sales_start', models.DateTimeField(blank=True, help_text='When ticket sales begin (optional)', null=True)),
                ('sales_end', models.DateTimeField(blank=True, help_text='When ticket sales end (optional)', null=True)),
                ('min_purchase', models.PositiveIntegerField(default=1, help_text='Minimum tickets per purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_purchase', models.PositiveIntegerField(default=10, help_text='Maximum tickets per purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('benefits', models.TextField(blank=True, help_text='Special benefits/perks (e.g., VIP lounge access, merch)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='Events.event')),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
                'ordering': ['event', 'created_at'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_number', models.PositiveIntegerField(help_text='Tier level (1 = cheapest, higher = more expensive)', validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(help_text='E.g., Tier 1, Tier 2, Early Bird', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(help_text='Number of tickets in this tier', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('sales_start', models.DateTimeField(blank=True, null=True)),
                ('sales_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='Tickets.tickettype')),
            ],
            options={
                'verbose_name': 'Ticket Tier',
                'verbose_name_plural': 'Ticket Tiers',
                'ordering': ['ticket_type', 'tier_number'],
                'unique_together': {('ticket_type', 'name'), ('ticket_type', 'tier_number')},
            },
        ),
        migrations.CreateModel(
            name='DayPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField(blank=True, help_text='Day number (null for All Days pass)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(help_text='E.g., Day 1, Day 2, All Days Pass', max_length=50)),
                ('date', models.DateField(blank=True, help_text='Specific date for this day pass', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(help_text='Number of passes available for this day', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_all_days', models.BooleanField(default=False, help_text="True if this is an 'All Days' pass")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_passes', to='Tickets.tickettype')),
            ],
            options={
                'verbose_name': 'Day Pass',
                'verbose_name_plural': 'Day Passes',
                'ordering': ['ticket_type', 'day_number'],
                'unique_together': {('ticket_type', 'day_number'), ('ticket_type', 'name')},
            },
        ),
    ]
