# Generated by Django 5.2.7 on 2025-11-05 05:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_banner_image_alter_event_thumbnail_image'),
        ('Orders', '0003_alter_order_buyer_phone'),
        ('Tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, help_text='Human-readable ticket number (auto-generated)', max_length=30, unique=True)),
                ('ticket_name', models.CharField(help_text='Ticket type name at time of creation', max_length=255)),
                ('tier_name', models.CharField(blank=True, help_text='Tier name if applicable', max_length=100)),
                ('day_name', models.CharField(blank=True, help_text='Day pass name if applicable', max_length=100)),
                ('event_date', models.DateTimeField(help_text='Event date/time (snapshot)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price paid for this ticket', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('qr_code_data', models.CharField(blank=True, help_text='Unique QR code data for verification', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_used', models.BooleanField(default=False, help_text='Has ticket been scanned?')),
                ('used_at', models.DateTimeField(blank=True, help_text='When ticket was scanned', null=True)),
                ('attendee_name', models.CharField(blank=True, help_text='Name of person attending with this ticket', max_length=255)),
                ('attendee_email', models.EmailField(blank=True, help_text='Email of person attending', max_length=254)),
                ('attendee_phone', models.CharField(blank=True, help_text='Phone of person attending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_pass', models.ForeignKey(blank=True, help_text='Specific day pass if day-based pricing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.daypass')),
                ('event', models.ForeignKey(help_text='Event this ticket is for', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Events.event')),
                ('order_item', models.ForeignKey(help_text='The order item this ticket belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Orders.orderitem')),
                ('scanned_by', models.ForeignKey(blank=True, help_text='Staff member who scanned ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket_tier', models.ForeignKey(blank=True, help_text='Specific tier if tiered pricing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.tickettier')),
                ('ticket_type', models.ForeignKey(help_text='Type of ticket', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.tickettype')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_number'], name='Tickets_tic_ticket__b58fc8_idx'), models.Index(fields=['qr_code_data'], name='Tickets_tic_qr_code_83fbf7_idx'), models.Index(fields=['event', 'status'], name='Tickets_tic_event_i_5376fe_idx'), models.Index(fields=['order_item'], name='Tickets_tic_order_i_6f188d_idx')],
            },
        ),
    ]
