# Generated by Django 5.2.7 on 2025-11-20 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0002_initial'),
        ('Tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scanned_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who scanned ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_tier',
            field=models.ForeignKey(blank=True, help_text="For 'tiered' pricing: Specific tier (VIP, General, etc.)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.tickettier'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='Events.event'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='Tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(help_text='Type of ticket', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='daytierprice',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_tier_prices', to='Tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='daypass',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_passes', to='Tickets.tickettype'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('event', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tickettier',
            unique_together={('ticket_type', 'name'), ('ticket_type', 'tier_number')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='Tickets_tic_ticket__b58fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['qr_code_data'], name='Tickets_tic_qr_code_83fbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'status'], name='Tickets_tic_event_i_5376fe_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order_item'], name='Tickets_tic_order_i_6f188d_idx'),
        ),
        migrations.AddIndex(
            model_name='daytierprice',
            index=models.Index(fields=['ticket_type', 'day_number', 'tier_number'], name='Tickets_day_ticket__fd7cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='daytierprice',
            index=models.Index(fields=['is_active'], name='Tickets_day_is_acti_d92b1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='daytierprice',
            unique_together={('ticket_type', 'day_name', 'tier_name'), ('ticket_type', 'day_number', 'tier_number')},
        ),
        migrations.AlterUniqueTogether(
            name='daypass',
            unique_together={('ticket_type', 'day_number'), ('ticket_type', 'name')},
        ),
    ]
