# Generated by Django 5.2.7 on 2025-11-18 04:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='day_pass',
            field=models.ForeignKey(blank=True, help_text="For 'day_based' pricing: Specific day pass", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.daypass'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_tier',
            field=models.ForeignKey(blank=True, help_text="For 'tiered' pricing: Specific tier (VIP, General, etc.)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.tickettier'),
        ),
        migrations.CreateModel(
            name='DayTierPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField(help_text='Day number (1, 2, 3, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('day_name', models.CharField(help_text='E.g., Day 1, Day 2, Friday, Saturday', max_length=50)),
                ('date', models.DateField(blank=True, help_text='Specific date for this day', null=True)),
                ('tier_number', models.PositiveIntegerField(help_text='Tier level (1 = VIP/highest, 2 = General, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('tier_name', models.CharField(help_text='E.g., VIP, General Admission, Regular', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this Day + Tier combination', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(help_text='Number of tickets available for this Day + Tier combination', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Number sold for this combination')),
                ('sales_start', models.DateTimeField(blank=True, null=True)),
                ('sales_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this combination currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_tier_prices', to='Tickets.tickettype')),
            ],
            options={
                'verbose_name': 'Day + Tier Price',
                'verbose_name_plural': 'Day + Tier Prices',
                'ordering': ['ticket_type', 'day_number', 'tier_number'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='day_tier_price',
            field=models.ForeignKey(blank=True, help_text="For 'tier_and_day' pricing: Specific Day+Tier combination", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='Tickets.daytierprice'),
        ),
        migrations.AddIndex(
            model_name='daytierprice',
            index=models.Index(fields=['ticket_type', 'day_number', 'tier_number'], name='Tickets_day_ticket__fd7cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='daytierprice',
            index=models.Index(fields=['is_active'], name='Tickets_day_is_acti_d92b1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='daytierprice',
            unique_together={('ticket_type', 'day_name', 'tier_name'), ('ticket_type', 'day_number', 'tier_number')},
        ),
    ]
