# Generated by Django 5.2.7 on 2025-11-03 20:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
        ('Tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, help_text='Human-readable order number (auto-generated)', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Total before fees and discounts', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform service fee', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount applied', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final amount to be paid', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('promo_code', models.CharField(blank=True, help_text='Promo code applied (if any)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Customer notes or special requests')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Pending orders expire after this time', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per ticket at time of purchase', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='quantity * unit_price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ticket_name', models.CharField(help_text='Ticket type name at time of purchase', max_length=255)),
                ('tier_name', models.CharField(blank=True, help_text='Tier name if applicable', max_length=100)),
                ('day_name', models.CharField(blank=True, help_text='Day pass name if applicable', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_pass', models.ForeignKey(blank=True, help_text='Specific day pass if day-based pricing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Tickets.daypass')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Orders.order')),
                ('ticket_tier', models.ForeignKey(blank=True, help_text='Specific tier if tiered pricing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Tickets.tickettier')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Tickets.tickettype')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='Orders_orde_created_b1a8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='Orders_orde_user_id_801521_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event', '-created_at'], name='Orders_orde_event_i_657551_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='Orders_orde_status_ab6a61_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='Orders_orde_order_n_18de59_idx'),
        ),
    ]
