# Generated by Django 5.2.7 on 2025-11-20 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
        ('Tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='day_pass',
            field=models.ForeignKey(blank=True, help_text='Specific day pass if day-based pricing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Tickets.daypass'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='day_tier_price',
            field=models.ForeignKey(blank=True, help_text='Specific day+tier combination if tier_and_day pricing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Tickets.daytierprice'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket_tier',
            field=models.ForeignKey(blank=True, help_text='Specific tier if tiered pricing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Tickets.tickettier'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Tickets.tickettype'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_id'], name='Orders_webh_event_i_e89943_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['-processed_at'], name='Orders_webh_process_dde45d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='Orders_orde_created_b1a8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='Orders_orde_user_id_801521_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event', '-created_at'], name='Orders_orde_event_i_657551_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='Orders_orde_status_ab6a61_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='Orders_orde_order_n_18de59_idx'),
        ),
    ]
