# Generated by Django 5.2.7 on 2025-11-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Stripe event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Event type (e.g., payment_intent.succeeded)', max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, help_text='Event payload for debugging', null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['event_id'], name='Orders_webh_event_i_e89943_idx'), models.Index(fields=['-processed_at'], name='Orders_webh_process_dde45d_idx')],
            },
        ),
    ]
