# Generated by Django 5.2.7 on 2025-11-05 04:36

import Common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_webhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=11, validators=[Common.validators.PhoneNumberValidator()]),
        ),
    ]
