# Generated by Django 5.2.7 on 2025-11-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_order_buyer_phone'),
        ('Tickets', '0003_alter_ticket_day_pass_alter_ticket_ticket_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='day_tier_price',
            field=models.ForeignKey(blank=True, help_text='Specific day+tier combination if tier_and_day pricing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Tickets.daytierprice'),
        ),
    ]
